In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model

In [3]:
df = pd.read_csv("D://newai/Material/ML/2_linear_reg_multivariate/homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
df.bedrooms.median()

4.0

# fillna --> NaN

In [5]:
df.bedrooms.fillna(4, inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
area = df.drop("price", axis="columns")
area

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [7]:
price = df.price
price

0    550000
1    565000
2    610000
3    595000
4    760000
5    810000
Name: price, dtype: int64

In [8]:
model = linear_model.LinearRegression()
model

LinearRegression()

In [13]:
model.fit(area, price)

LinearRegression()

In [14]:
model.predict([[3000, 3, 40]])

C:\Users\Mohamed Makki\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

# price = m * area + m * bedrooms + m * age + c

In [15]:
model.coef_ # values m in area , m in bedrooms , m in age 

array([  112.06244194, 23388.88007794, -3231.71790863])

In [16]:
model.intercept_ # value c

221323.0018654043

**Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old**

In [21]:
model.predict([[3000, 3, 40]])

C:\Users\Mohamed Makki\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [23]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.0018654043

498408.2515740243

# Exercise

In exercise folder (same level as this notebook on github) there is **hiring.csv**. This file contains hiring statics for a firm such as experience of candidate, his written test score and personal interview score. Based on these 3 factors, HR will decide the salary. Given this data, you need to build a machine learning model for HR department that can help them decide salaries for future candidates. Using this predict salaries for following candidates,


**2 yr experience, 9 test score, 6 interview score**

**12 yr experience, 10 test score, 10 interview score**


In [62]:
data = pd.read_csv("D://newai/Material/ML/2_linear_reg_multivariate/Exercise/hiring.csv")
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# fillna --> NaN

In [63]:
data["test_score(out of 10)"].fillna(data["test_score(out of 10)"].min(), inplace=True)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    6.0                           7      72000
7     eleven                    7.0                           8      80000

In [69]:
data.fillna("zero", inplace=True)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    6.0                           7      72000
7     eleven                    7.0                           8      80000

In [75]:
from word2number import w2n
data.experience = data.experience.apply(w2n.word_to_num)
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    6.0                           7      72000
7          11                    7.0                           8      80000

In [91]:
f = data.experience.to_list()
f[0] = 1
f[1] = 0
data.experience = f
data

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           1                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    6.0                           7      72000
7          11                    7.0                           8      80000

In [92]:
x = data.drop("salary($)", axis="columns")

In [93]:
y = data["salary($)"]

In [94]:
model = linear_model.LinearRegression()

In [95]:
model.fit(x, y)

LinearRegression()

# 2 yr experience, 9 test score, 6 interview score

In [96]:
model.predict([[2, 9, 6]])

C:\Users\Mohamed Makki\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53660.32674957])

# 12 yr experience, 10 test score, 10 interview score

In [97]:
model.predict([[12, 10, 10]])

C:\Users\Mohamed Makki\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([94858.81492319])

In [98]:
model.score(x, y)

0.9673945616172213

In [99]:
model.coef_

array([3097.53718605, 2363.56986101, 1964.88661302])

In [100]:
model.intercept_

14403.803950255999